### ISSUE TITLE
Padded encoding?

### ISSUE THREAD

**Issue by rtfeldman** [truqu/elm-base64#22]
I'm not sure from the docs if the encoded Base64 strings are padded or not. (I assume not.)

Context: I'm working on sending stuff to Mixpanel, and [they only accept padded Base64 requests](https://mixpanel.com/help/reference/http#base64).

> Mixpanel will only accept padded Base64 requests.

**Comment by zwilias** [comment]
They are, in fact, padded. For context, "padded" just means that trailing null-sixtuples are encoded as `=` rather than chomped off.

I've been thinking that the docs for this package could use some more info and examples. Thanks for the reminder 👍

**Comment by rtfeldman** [comment]
Great, thanks!

**Comment by zwilias** [comment]
Published more informative docs in [2.0.3](http://package.elm-lang.org/packages/truqu/elm-base64/2.0.3/Base64)
