### ISSUE TITLE
Use better approach for encoding 

### ISSUE THREAD

**Issue by justgook** [truqu/elm-base64#23]
[here](https://github.com/truqu/elm-base64/blob/master/src/Base64/Encode.elm#L54) is problem..

[here](http://package.elm-lang.org/packages/pablohirafuji/elm-char-codepoint/latest) bis solution

> The charCodeAt() method returns an integer between 0 and 65535 representing the UTF-16 code unit at the given index (the UTF-16 code unit matches the Unicode code point for code points representable in a single UTF-16 code unit, but might also be the first code unit of a surrogate pair for code points not representable in a single UTF-16 code unit, e.g. Unicode code points > 0x10000). If you want the entire code point value, use codePointAt()

```
Char.toCode '𝔸' == 55349
Char.fromCode 55349 == '�'


Char.CodePoint.fromChar '𝔸' == 120120
Char.CodePoint.toString 120120 == "𝔸"

**Comment by zwilias** [comment]
This library already accounts for that case.

```elm
> Base64.encode "𝔸"
"8J2UuA==" : String
> Base64.decode "8J2UuA=="
Ok "𝔸" : Result.Result String String
```

The reason we can get away with `Char.toCode` theree is because the `Char` there comes from `String.toList`, which splits that single "character" into a surrogate pair:

```elm
> String.toList "𝔸" |> List.map Char.toCode
[55349,56632] : List Char.KeyCod
```
