### ISSUE TITLE
Decoding crashes Elm with "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by mordrax** [truqu/elm-base64#25]
Decoding a base64 file crashes with a "Maximum call stack size exceeded" error.

Using Elm 0.19.1, elm-base64 v2.0.4. Unfortunately I cannot shared the base64 file.

![image](https://user-images.githubusercontent.com/4709169/68000041-9ecb1b80-fcb2-11e9-8098-6c08bc067a86.png)

**Comment by mordrax** [comment]
I just realised that it's trying to decode a payload size of 20megs. Most websites become unresponsive and I wouldn't expect elm-base64 to be any different.

**Comment by zwilias** [comment]
Heh, interesting that it's the regex match that fails!
